Traceback (most recent call last):
  File "provideAPI.py", line 24, in <module>
    app.run(host='0.0.0.0',port=8802,debug=True)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 780, in run_simple
    s.bind((hostname, port))
OSError: [Errno 48] Address already in use

***Repl Closed***
